server:
  port: 8090
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:medium_test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
custom:
  site:
    baseUrl: "http://localhost:${server.port}"
  tempDirPath: c:/temp/medium_test/temp
  genFile:
    dirPath: c:/temp/medium_test